### ISSUE TITLE
[1차 세미나] 생각, 기본, 심화 과제

### ISSUE THREAD

**Issue by Hong0329** [DO-SOPT-SERVER/Hong0329#1]
## ✏️ TO-DO

- [x] 생각 과제
- [x] 자바 기본 과제
- [x] 스프링 기본 과제
- [x] 스프링 심화 과제

## 📃 참고사항

1주차 생각과제 https://canyon-rhythm-70f.notion.site/1-a4be523df93941fdad0b541986b8b173?pvs=4
